### ISSUE TITLE
分页

### ISSUE THREAD

**Issue by AkkoSpace** [AkkoSpace/fenxiang-frontend#4]
```vue
<a-pagination
  :current="pagination.current"
  :page-size="pagination.pageSize"
  :total="pagination.total"
  class="custom-pagination"
  show-page-size
  show-total
  @change="onPageChange"
 />
```

```less
.custom-pagination {
  position: absolute;
  right: 20px;
  bottom: 20px;
}

```
